### ISSUE TITLE
Improve error message when an unknown protocol is used to create a PersistentResource

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#10]
When an unknown protocol is given to the [PersistenceBackendFactoryRegistry](https://github.com/atlanmod/NeoEMF/blob/master/core/src/main/java/fr/inria/atlanmod/neoemf/datastore/PersistenceBackendFactoryRegistry.java), a RuntimeException is thrown, but the message is not clear

`throw new RuntimeException("Can not find a factory for the given type " + factoryId);`

**Comment by yvernageau** [comment]
Replaced by the following message in #49 : 
```
"No factory is registered to process the URI scheme %s. Use the %s.register() method first",
                uriScheme,
                PersistenceBackendFactoryRegistry.class.getName()
```
Is that better ?
