### ISSUE TITLE
Store large EMF models in MongoDB.

### ISSUE THREAD

**Issue by AKJac** [atlanmod/NeoEMF#104]
Hi,
 I want to persisted EMF models in MongoDB,how I can do use NeoEMF to implement this?

Regards,
Zhicheng Chen

**Comment by sunye** [comment]
Dear Zhicheng,

Currently, MongoDB is not supported. However, there is fork of NeoEMF which aims at supporting MongoDB:

https://github.com/natinusala/NeoEMF

Kind regards,

Gerson
