### ISSUE TITLE
Registering PersistenceFactory with multiple dynamic ecores

### ISSUE THREAD

**Issue by petrotta** [atlanmod/NeoEMF#105]
Hi, 

When I load and register multiple dynamic ecores, then invoke setEFactoryInstance(), only the last registered EPackage will maintain the PersistenceFactory reference.

Example:

        EFactory thefactory = PersistenceFactory.getInstance();
        dynamicEP1.setEFactoryInstance(thefactory);
        dynamicEP2.setEFactoryInstance(thefactory);  // now dynamicEP1 getFactoryInstance()==null

This appears to be due to the org.eclipse.emf.ecore.impl.EPackageImpl setEFactoryInstance eInverseRemove. Since there is only one instance of the PersistenceFactory, I am not sure how to avoid this.

Thanks!

**Comment by petrotta** [comment]
I solved my problem by creating a duplicate of the 1.0.2 PersistenceFactory without the singleton design pattern.  Perhaps there is a better way:

public class PersistenceFactoryMod extends EFactoryImpl implements EFactory {

    public PersistenceFactoryMod() {
    }

    @Override
    public PersistentEObject create(EClass eClass) {
        DefaultPersistentEObject object = new DefaultPersistentEObject();
        object.eSetClass(eClass);
        return object;
    }

}

**Comment by yvernageau** [comment]
Fixed in the latest release (`2.0.0`).
