### ISSUE TITLE
Update site for version 2.0.0 is broken

### ISSUE THREAD

**Issue by arcanefoam** [atlanmod/NeoEMF#107]
Hi,
Installation form the update site fail. The error suggests that the update site plugin itself is correctly deployed (i.e. the categories, plugins to install and licences are retrieved) but the actual jars of the plugins are not found:

`An error occurred while collecting items to be installed
session context was:(profile=_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.core_2.0.0.jar.
https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.core_2.0.0.jar
Artifact not found: https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.data.berkeleydb_2.0.0.jar.
https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.data.berkeleydb_2.0.0.jar
Artifact not found: https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.data.blueprints.core_2.0.0.jar.
https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.data.blueprints.core_2.0.0.jar
Artifact not found: https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.data.blueprints.neo4j_2.0.0.jar.
https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.data.blueprints.neo4j_2.0.0.jar
Artifact not found: https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.data.hbase_2.0.0.jar.
https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.data.hbase_2.0.0.jar
Artifact not found: https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.data.mapdb_2.0.0.jar.
https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.data.mapdb_2.0.0.jar
Artifact not found: https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.eclipse.examples.core_2.0.0.jar.
https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.eclipse.examples.core_2.0.0.jar
Artifact not found: https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.eclipse.ui_2.0.0.jar.
https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.eclipse.ui_2.0.0.jar
Artifact not found: https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.io_2.0.0.jar.
https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/fr.inria.atlanmod.neoemf.io_2.0.0.jar
Artifact not found: https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/org.atlanmod.commons_1.0.4.jar.
https://atlanmod.github.io/NeoEMF/releases/latest/plugin/plugins/org.atlanmod.commons_1.0.4.jar`

**Comment by sunye** [comment]
Dear Horacio,

We are facing some issues when creating an update site on GitHub, as we were doing in version 1.x.

We will probably migrate our update site to a private server. For now, you can find the last NeoEMF version at Bintray:

https://dl.bintray.com/sunye/neoemf/

I'm sorry for the inconvenient. Best regards,

Gerson

**Comment by yvernageau** [comment]
For an unknown reason, it seems the `plugins` directory does not exists in the latest release.
The package must be rebuild.
