### ISSUE TITLE
Unable to create multiple connections to Neo4JGraph

### ISSUE THREAD

**Issue by krish-2214** [atlanmod/NeoEMF#109]
I am using below code snippet to create a resource connection to Neo4j. Is there a possible way to create another connection to the Neo4j db simultaneously before closing the existing connection. I am getting below exception when attempting to create multiple connections:
`fr.inria.atlanmod.neoemf.data.InvalidDataStoreException: java.lang.RuntimeException: GraphFactory could not instantiate this Graph implementation [com.tinkerpop.blueprints.impls.neo4j.Neo4jGraph].
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: fr.inria.atlanmod.neoemf.data.InvalidDataStoreException: java.lang.RuntimeException: GraphFactory could not instantiate this Graph implementation [com.tinkerpop.blueprints.impls.neo4j.Neo4jGraph].`

**Code snippet:**
` PersistenceBackendFactoryRegistry.register(BlueprintsURI.SCHEME, BlueprintsPersistenceBackendFactory.getInstance());
    PersistentResource persistentResource = null;
    ResourceSet rSet = new ResourceSetImpl();
    rSet.getResourceFactoryRegistry().getProtocolToFactoryMap().put(BlueprintsURI.SCHEME,
        PersistentResourceFactory.getInstance());
    File file = new File(neoEmfDbPath);
    URI createFileURI = PersistenceURI.createFileURI(file, BlueprintsURI.SCHEME);
    if (file.exists()) {
      persistentResource = (PersistentResource) rSet.getResource(createFileURI, true);
    }
    if (persistentResource == null) {
      persistentResource = (PersistentResource) rSet.createResource(createFileURI);
    }
    Map<Object, Object> options = new HashMap<Object, Object>();
    options.put(BlueprintsResourceOptions.GRAPH_TYPE, BlueprintsNeo4jResourceOptions.GRAPH_TYPE_NEO4J);
    persistentResource.save(options);
    return persistentResource;`

**Comment by gdaniel** [comment]
Hi,

NeoEMF relies on an embedded neo4j database that doesn't allow multiple connections. What is your use case? If I remember well there is a way to retrieve the low-level neo4j graph from the PersistentResource interface, would it be helpful?
