### ISSUE TITLE
Not able to disable logging in Neo4j Graph

### ISSUE THREAD

**Issue by i-am-senthil** [atlanmod/NeoEMF#112]
The  Neo4j Graph graph seems to be fast when a new resource is created. But over a period of time the database size grows and the connection creation takes a lot of time and eventually database operations become slow.

On Inspection I could see a lot of .log files as attached in the video gets created. Also, the **message.log** file size grows enormously(in GBs). 

I manually go to the DB folder and delete these files and the database becomes faster once again.

Is there a provision to disabled this logging or some configuration to control the log rotation? I  cannot find any resources online. 

Any help here would help me resolve a lot of issues.

Thanks

**Comment by gdaniel** [comment]
Hi,
The `BlueprintsNeo4jConfig` lets you specify native options for the neo4j backend. I don't remember the exact options you need to set in neo4j to shorten the size of the logs but you can probably find them in the neo4j documentation. Keep in mind that NeoEMF uses an old version of neo4j (2.1.x), so the properties may be different from the latest version's documentation.

It's also important to note that Neo4j logs are logical logs, so if you completely disable them you lose some nice feature like rollbacks.
