### ISSUE TITLE
NeoEmf- MongoDb developer guide

### ISSUE THREAD

**Issue by i-am-senthil** [atlanmod/NeoEMF#114]
Hello Team,
 Currently we are using Neo4j embedded database in our application. This works fine for our VM based architecture. 
However, there is a migration in progress and our application is being moved to Cloud Foundry. This pose a major challenge to us  and we are forced to use cloud found container storage to hold this embedded db. 
If the cloud foundry containers crashes/restarts due to platform update, existing container will be destroyed and reinstated and all our data is lost.

So we are planning to use MongoDb cluster instead of Neo4j graph. I have few queries regarding the same:

1. Is the NeoEmf-MongoDb implementation stable?
2. Where can I find the developer guide for using NeoEMF with MongoDB. I tried just using the api doc and couldn't do it successfully. 
3. Currently, we use NeoEmf version 1.x, is there a guide to migrate to version 2.x?

I know the query list is tool long but our use case is critical and would be a blocker for migration. 

Any of  your valuable inputs are highly appreciated

Thanks
Senthil

PS: Our team is new to neomf implementation

**Comment by sunye** [comment]
Dear Senthil,

1. The MongoDB backend implementation is stable, however the performances are worser than using embedded databases. If you need a Client/Server architecture, you should take a look at Eclipse CDO.
2. There are some explanations in the Wiki pages, but none about MongoDB. Pull requests are welcome.
3. There is no specific tool to migrate from version 1.x, the best option is to use version 1 to export to XMI and then use version 2 to import to a new database. Again, Pull requests are welcome. 

Best regards,

Gerson

**Comment by i-am-senthil** [comment]
@sunye : Thanks for the input. We Will explore the possibility
