### ISSUE TITLE
Invalid return for eInternalContainer

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#12]
The return of eInternalContainer is not always consistent with EMF standard implementation.
Fixing it may cause important performance problems (need to be studied).

See this [test case](https://github.com/atlanmod/NeoEMF/blob/master/tests/src/test/java/fr/inria/atlanmod/neoemf/tests/LoadedResourceContainerTest.java) for examples (tests have been commented to avoid build failure)

**Comment by yvernageau** [comment]
Fixed in #69 : The stores are updated according to the EMF calls, so that the backends are always synchronized. There is no longer custom processing during `set()` and `add()`.
