### ISSUE TITLE
log4j security update for neoemf-core 1.0.x version

### ISSUE THREAD

**Issue by i-am-senthil** [atlanmod/NeoEMF#126]
Hello Team,

We are using the neoemf v1.0.x in our applications.  To overcome the log4j vulnerabilities, we have manually repacked the neoemf-core.jar with a secure version of log4j(2.17.1) for time being.

Is there any release planned for this vulnerability fix any soon?

**Comment by sunye** [comment]
Hello Senthil,

Sure, we can release a new version. Did you consider using version 2.0.x?

**Comment by sunye** [comment]
Senthil,

I just released version 1.0.3 on Maven Central. Please notice that we changed the `groupId`, which is now `org.atlanmod.neoemf`.

The Eclipse plugins are available on this update site:
https://atlanmod.github.io/NeoEMF/releases/1.0.3/plugin/

**Comment by i-am-senthil** [comment]
> Hello Senthil,
> 
> Sure, we can release a new version. Did you consider using version 2.0.x?

**Comment by i-am-senthil** [comment]
@sunye ,

We tried using 2.0 earlier but faced a few issues as there are changes in the way we consume your APIs. Since our app is cloud-native, We also wanted to get rid of files-based blueprints backend and move towards a more decentralized DB like MongoDB.  However, there are no stable examples or developer guides to illustrate the implementation. 
We are running on stringent timelines and don't have adequate expertise on NeoEMF to make such a switch and thus sticking to v1.0.x.

**Comment by i-am-senthil** [comment]
@sunye,
Sorry, I couldn't find v1.0.3 in the maven repo. The only version listed there is 2.0.1

**Comment by sunye** [comment]
You are welcome!

There is already some documentation in the Wiki section. If you think some parts should be improved, don't hesitate to create another issue or even better, propose a pull request! You can also send me an email. We would appreciate to learn about the way you use NeoEMF.
