### ISSUE TITLE
Installing only the core plugin installs all the supported backend + ui

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#14]
This should only install the core plugin, specific backends are optionnal

**Comment by yvernageau** [comment]
The `core` features reference the `ui` plugin, which in turn reference Blueprints and Map implementations in its `MANIFEST.MF` as `Required-Bundle`. There is surely something to see on that side.

**Comment by yvernageau** [comment]
Since f98306c6b7f63aa567bd0101f0aab526817c90e1: All elements related to a `BackendFactory` can be found by using reflection: these direct dependencies are no longer necessary, and have been removed.
