### ISSUE TITLE
Errors on loading moved Blueprints Resource 

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#15]
If a Blueprints resource is moved the properties contained in config.properties are not consistent with the new db location (`blueprints.neo4j.directory` and `blueprints.neo4j.conf.store_dir`) and the database fails to load.

Need to be studied:
- When does this happen
- For which property
- Is it the same for MapDB

**Comment by yvernageau** [comment]
This problem is specific for Blueprints that saves its own properties, including the current path of the store. Is this properties file required ?

**Comment by yvernageau** [comment]
Fixed with #69 : The `blueprints.***.directory` property is overwritten in all cases by the current path: If a datastore already exists, then this property is updated with the new path, otherwise, the property is unchanged.
