### ISSUE TITLE
[Eclipse] Test model is not generated by Eclipse build

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#26]
If you clone the repository and add all the projects to Eclipse the build does not generate java-gen folder.
This issue is only related to Eclipse build, if the project is build with the command line generated classes are correctly generated.

@yvernageau can you have a look on that?

**Comment by yvernageau** [comment]
See [the wiki](https://github.com/atlanmod/NeoEMF/wiki/Code-generation-with-Maven#known-issues) for more information.
