### ISSUE TITLE
Remove transient store creation on resource shutdown?

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#27]
Creating a transient store / backend on resource shutdown consumes memory and may be problematic for the maven build, where all the tests are executed in the same JVM, creating many transient (and useless) stores.

**Comment by yvernageau** [comment]
It's a strange behavior, because the transient `Store` created when closing is empty. The problem may comes from elsewhere.

We should perhaps create a `ClosedStoreDecorator` to avoid changes to a closed `Resource` ?

**Comment by yvernageau** [comment]
Fixed in #69: A `Store` is no longer copied when the associated `Resource` is unloading: a `Resource` should not be called if it's not loaded.

This can also help for issue #61.
