### ISSUE TITLE
Created transient store contents

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#28]
Does transient stores contain the element of the old persistent store when a shutdown is called?
Maybe it is not needed (need to be compared with standard [Resource.unload()](http://download.eclipse.org/modeling/emf/emf/javadoc/2.4.3/org/eclipse/emf/ecore/resource/Resource.html#unload%28%29) behaviour)

**Comment by yvernageau** [comment]
No, when a `PersistentResource` is closed/unloaded, the new `TransientStore` is empty. A new loading is required to retrieve the content.

Copy the content from the persistent `Store` to the transient `Store` can cause important overhead, depending of the size of the `Resource`

**Comment by yvernageau** [comment]
Related to #27
