### ISSUE TITLE
[test-commons] Generated code errors

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#32]
Generated code does not contain parametrized types for Collection returns.
For example `SampleModel.getSampleModelContentObject()` returns an `EList` instead of an `EList<SampleModelContentObject>`.

**Comment by yvernageau** [comment]
Issue solved. See [the wiki](https://github.com/atlanmod/NeoEMF/wiki/Code-generation-with-Maven#generate-at-a-specific-jdk-level) for more information
