### ISSUE TITLE
Default eContents for EObject subclasses is not efficient

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#33]
It is implemented using a containment list, and the get(idx) iterates all elements before idx, creating many unnecessary database calls.

**Comment by gdaniel** [comment]
Partially solved for get() method

**Comment by yvernageau** [comment]
Solved in #69 : All EMF `Iterator`s and `Collection`s have been reimplemented, using batch methods (such as `#getAll`, `#addAll`) to avoid atomic calls to the database.
