### ISSUE TITLE
Latencies on UI

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#34]
There are still some latencies in the browser. 
It seems to be related to #33: some operations have to be optimized in case we are using a database (like recursive contains chain)

**Comment by gdaniel** [comment]
Partially solved with dedicated caches, still some optimizations have to be done

**Comment by yvernageau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Still some latencies in UI](https://trello.com/c/WSMcsxtb/72-still-some-latencies-in-ui)
