### ISSUE TITLE
Map implementation too slow when importing XMI

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#37]
Need to be investigated, maybe a `PersistentResourceImpl::resource(Resource)` error

**Comment by gdaniel** [comment]
Database size too big compared to previous versions (75.5M vs. 39.8M for 20M XMI file)

**Comment by yvernageau** [comment]
The excessive database size may be related to the different `ClassDescirptor` and `SingleFeatureKey`, representing the containers, which are saved several times, even if they are identical.

These links are mainly many-to-one links, especially for metaclasses.

Separated maps could solve this issue: 
- one map for the descriptors
- one map for the associations to the related `Id`s

**Comment by yvernageau** [comment]
The duration of the import is now globally identical between the different implementations.

For better performance, the direct import of the `neoemf-io` module is up to 15 times more efficient than the standard EMF import.
