### ISSUE TITLE
NeoEditor captures NoSuchMethodErrors on setSelection but does not handle them

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#52]
There is a try .. catch that avoid nasty Eclipse-level error message. This error occurs when an editor is opened with a resource loaded using a Dynamic EPackage. The command creation creates a DynamicEObject somehow, that is sent to a contains methods that fails on the proxy capture of `id()`

This exception need to be handled / avoided, by supporting Dynamic EMF in the Editor.

**Comment by yvernageau** [comment]
Since 730ac385825034e950fc35867035a38e46aef3d7: This exception is now handled internally, and has been replaced by an `UnsupportedOperationException`.
