### ISSUE TITLE
Bad performance when unloading resource contents

### ISSUE THREAD

**Issue by sunye** [atlanmod/NeoEMF#61]
Method `Resource::unload()` seems to call the `indexOf()` method for persistent referenced, generating an important overload.

**Comment by yvernageau** [comment]
This may be related to the `ResourceImpl#getUnloadingContents()` method that creates a full copy of the resource's content, to define the proxy and clear the adapters for each object (if supported) with the`ResourceImpl#unloaded(InternalEObject)` method.

**Comment by yvernageau** [comment]
`PersistentEObject`s are created on demand, so the call to `ResourceImpl#getUnloadingContents()` when unloading is not relevant. This method now returns a `Collections.emptyList()` as specified in the method description.
