### ISSUE TITLE
inconsistency problem when copying resource contents

### ISSUE THREAD

**Issue by sunye** [atlanmod/NeoEMF#62]
When the contents of a *normal* resource are copied to a persistent one, using the following code:
```java
targetResource.getContents().addAll(sourceResource.getContents());
```
The contents remain in both contents, causing inconsistency. It seems that the handshake is not treated correctly.

**Comment by gdaniel** [comment]
Need to check the behavior of XMI resources
`xmiResource.getContents().addAll(sourceXMIResource.getContents());`

The links should be removed, but we need to be sure about that.

**Comment by gdaniel** [comment]
Should be put in the tutorial / wiki (see #66)

**Comment by yvernageau** [comment]
A call to `EcoreUtil#copyAll` is no longer necessary
