### ISSUE TITLE
PersistentResource.clear() throws NPE on empty resource

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#64]
Found in Blueprints module, may also appear in other ones. The NPE commes from toArray on the dummy root container. Since no element has been saved before this dummy object has not been added to the database, and the underlying query fails.

Need to check if we should handle this error at the toArray() level, or the clear() level.

**Comment by yvernageau** [comment]
Fixed with #69 : If an `Id` is not found in `Backend`s, then an empty array is returned.
