### ISSUE TITLE
NPE and inconsistencies for containment list

### ISSUE THREAD

**Issue by timeraider4u** [atlanmod/NeoEMF#7]
Dear all, when I execute for example 

1. @Test public void testMy2C() {
2. 		My2Factory factory = My2Factory.eINSTANCE;
3. 		my2.A a = factory.createA();
4. 		Assert.assertNotNull(a);
5. 		EList<my2.B> list = a.getList();
6. 		Assert.assertNotNull(list);
7. 		Assert.assertTrue(list.isEmpty());
8. 	}

I get a null pointer exception on the last assertion.

I am using NeoEMF MapDB Adapter 0.0.1.201510191303 and NeoEMF Persistence Framework version 0.0.1.201510191303, both from the update site.

Steps to reproduce:
1.) Download sample project My - git clone https://github.com/timeraider4u/testing/
2.) Import sample project My into Eclipse
3.) Execute JUnit test case in My/src/test/MyTest.java

**Comment by gdaniel** [comment]
Hi, thanks for the feedback.

I have found the problem, it seems that empty lists are not properly handled if you use the default TransientEStore.
I'll fix that as soon as possible, several methods in the TransientEStore for multi-valued features have to be tested before I can integrate the fix.

For your information, the TransientEStore is provided with NeoEMF to handle Resource/EObject creation when no Persistence backend is specified, but it is not a scalable implementation as Graph or the Map ones.
If you want to use MapDB implementation, please have a look on the wiki to know how to instantiate the backend properly.

One last thing, the test testMy2B() in your test case will always fail: a getter on a List instanciate an empty list if the attribute is not set, and thus `Assert.assertNull(a.getList())` cannot be true.

I keep this issue open until the corrections are integrated into the update site.

Gwendal

**Comment by timeraider4u** [comment]
Hi, thank you for your quick response and your detailed explanations. Looking forward for testing the bug fix ;-).

**Comment by timeraider4u** [comment]
fixed in newest version! Thank you very much :-).
