### ISSUE TITLE
neoemf-data map-core is not a valid bundle

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#73]
Map-core pom doesn't create an OSGI bundle, and makes Map-based implementation unusable when NeoEMF is installed in Eclipse (mapdb bundle cannot find MapBackend and throws a NoClassDefFound error).

This issue exists only on the development branch (last release is ok), and has been introduced in mapstore refactoring pull request.

**Comment by yvernageau** [comment]
This module no longer exists in #69 : no need to fix it in the `master` branch

**Comment by gdaniel** [comment]
This issue is now part of the latest release. It was actually a bad idea to ignore it in the `master` branch, even if it has been solved in #69.

**Comment by yvernageau** [comment]
This module doesn't appear in any release, just in the dev branch. And it should not be released, especially in the Maven repository because this artifact would only be used for a single version.

However, I can fix this problem on the `master` branch, if necessary.

**Comment by gdaniel** [comment]
as @yvernageau pointed out, this error only occurs in the master branch / latest snapshot. It will be fixed when #69 will be merged.
