### ISSUE TITLE
Accessing a model from HBase throws an obscure NPE if model's EPackages are not registered

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/NeoEMF#78]
The `resolveInstanceOf()` method embedded in the HBase store throws a NPE if one of the EPackages of the underlying model are not registered. We should throw a better exception that explains why the instance cannot be resolved.

Blueprints and MapDB backends may contain the same issue.

**Comment by yvernageau** [comment]
Since #69 : `ClassDescriptor#get()` throws a `NullPointerException` with the reason "Unable to find EPackage for URI: {uri}" when the concerned `EPackage` is not registered.
