### ISSUE TITLE
Store was closed

### ISSUE THREAD

**Issue by angel539** [atlanmod/NeoEMF#89]
Hi,

I am trying to have more than an instance of neoemf in my project in order to associate a neoemf datastore with an IProject of Eclipse. I mean, one neoemf datastore by IProject.

I control the **creation** of the Resource following the code next (for a MapDB BackEnd):

`PersistenceBackendFactoryRegistry.register(MapDbURI.SCHEME,
													MapDbPersistenceBackendFactory.getInstance());
		resourceSet.getResourceFactoryRegistry().getProtocolToFactoryMap() //scheme
													.put(MapDbURI.SCHEME, PersistentResourceFactory.getInstance());
		// 1. Creation
		try(PersistentResource persistentResource = 
					(PersistentResource) resourceSet.createResource(
						MapDbURI.createFileURI(
								new File(
										ResourcesPlugin.getWorkspace().getRoot().getLocation().toString() + "/models/" + name + ".mapdb"
									)
								)
						)){
			Map<String, Object> options = 
					MapDbOptionsBuilder.newBuilder().directWrite().cacheIsSet().cacheSizes().asMap();
	        persistentResource.save(options);
			//persistentResource.load(Collections.emptyMap()); // optional
			// 2. First population with a repositoryManager
			persistentResource.getContents().add(repositoryManager);
			// 3. Saving and unloading
			persistentResource.save(MapDbOptionsBuilder.noOption());
			persistentResource.unload();
			context.put(name, persistentResource);
		}
		catch (IOException exception) {
			ExtremoLog.logError(exception);
		}`

In other part of my project I create elements in the Resource using the EditingDomain to control the transactions...

`// 1. Loading
EditingDomain domainShared = ...
Map<String, Object> options = 
		    MapDbOptionsBuilder.newBuilder().directWrite().cacheIsSet().cacheSizes().asMap();
				persistentResource.load(options);
Command command = new RecordingCommand(domainShared, "Create element"){
					@Override
					protected void doExecute() {
						... // [1] create elements on the Resource...
//}
				//};
				
				//domainShared.getCommandStack().execute(command);
				// 3. Saving
				persistentResource.save(options);
				persistentResource.unload();
`

But in the creation of the elements [1] I always obtain this exception:

java.lang.IllegalAccessError: Store was closed
	at org.mapdb.StoreDirectAbstract.assertNotClosed(StoreDirectAbstract.kt:62)
	at org.mapdb.StoreDirect.getBinaryLong(StoreDirect.kt:553)
	at org.mapdb.IndexTreeListJava.treeGetBinary(IndexTreeListJava.java:238)
	at org.mapdb.IndexTreeListJava.treeGet(IndexTreeListJava.java:193)
	at org.mapdb.IndexTreeLongLongMap.get(IndexTreeLongLongMap.kt:77)
	at org.mapdb.HTreeMap.getprotected(HTreeMap.kt:629)
	at org.mapdb.HTreeMap.get(HTreeMap.kt:603)

Do you have any clue of what is happening? Are the options well defined? There is any incompatibility between using Transactions and the persistence based on neoemf?

All the best,

Ángel

**Comment by angel539** [comment]
Current version: 1.0.2

**Comment by yvernageau** [comment]
Hi,

It seems that your problem comes from `Resource#unload()`: this method unloads all content by closing the database. The same problem comes with the `try-with-resource` that implicitly call `PersistentResource#close()` at the end of the block.

Make sure that the call to `Resource#unload()` is done at the end of the execution, or when you are sure that no further calls to the resource will be made.

I hope this will help you.

Best regards,
Yoann

**Comment by angel539** [comment]
MapDbOptionsBuilder.newBuilder().directWrite().cacheIsSet().cacheSizes().asMap(); 

Thanks, and one more thing about the options. I am trying to improve the performance of my project (http://angel539.github.io/extremo/) saving several elements on the neoemf datastore. 

Do you know if in the options for the datastore based on MapDb there are some options that spend more time than others?

All the best,

Ángel
