### ISSUE TITLE
Invalid feature.xml file

### ISSUE THREAD

**Issue by abelgomez** [atlanmod/NeoEMF#90]
File `plugins/eclipse/features/fr.inria.atlanmod.neoemf.core.feature/feature.xml` contains invalid lines from an incorrectly managed merge betweens lines 51 and 55:

https://github.com/atlanmod/NeoEMF/blob/2729814b205b032bdf56483a99523cae601584b8/plugins/eclipse/features/fr.inria.atlanmod.neoemf.core.feature/feature.xml#L50-L56

**Comment by sunye** [comment]
Thanks for pointing it, Abel.
