### ISSUE TITLE
'Dynamic EMF not supported' exception while using static model

### ISSUE THREAD

**Issue by paulreuter** [atlanmod/NeoEMF#92]
Hello,

I have tried to migrate our XMLResource (not XMI) based models to use a NeoEMF backend. The model classes are generated with a NeoEMF migrated genmodel, using the snapshot update site. (1.0.3.20180218212248)

While loading and saving (XML), I encounter a "java.lang.UnsupportedOperationException: Dynamic EMF is not supported yet"

This happens when the xmlNsPrefixMap ( type DirectStoreMap ) is modified. Relevant call stack excerpt follows:

PersistentEObjectAdapter$PersistentEObjectInterceptor.resolve(InternalEObject) line: 212	
PersistentEObjectAdapter$PersistentEObjectInterceptor.intercept(Object, Method, Object[], MethodProxy) line: 194	
EStringToStringMapEntryImpl$$EnhancerByCGLIB$$62688f51.id() line: not available	
ReferenceConverter.convert(PersistentEObject) line: 49	
TransientStoreAdapter(AbstractStoreAdapter).contains(InternalEObject, EStructuralFeature, Object) line: 361	
DirectStoreMap$EntryList(DirectStoreList<E>).delegateContains(Object) line: 93	
DirectStoreMap$EntryList(DirectStoreList<E>).contains(Object) line: 262	
DirectStoreMap$EntryList(AbstractEList<E>).add(E) line: 297	
DirectStoreMap<K,V>(BasicEMap<K,V>).put(K, V) line: 585	
DirectStoreMap<K,V>(BasicEMap<K,V>).putAll(EMap<? extends K,? extends V>) line: 691	
SAXXMLHandler(XMLHandler).recordNamespacesSchemaLocations(EObject) line: 1306

**Comment by sunye** [comment]
Hi Paul,

Could you please share your code with us?

Thanks,

Gerson

**Comment by paulreuter** [comment]
Sorry, took a while to cut to the relevant portions. 
The main method in ExceptionRunner reproduces this issue for me.

[neoemf_dyn_emf_exception.zip](https://github.com/atlanmod/NeoEMF/files/1743881/neoemf_dyn_emf_exception.zip)

**Comment by paulreuter** [comment]
Ok, I had a little time to do some digging. The UnsupportedOperationException is a bit of a red herring. 

The underlying problem is: DirectStoreMap uses the 'newEntry' method of its ancestor EcoreEMap to create an entry of type EStringToStringMapEntryImpl (in this case; the type is a parameter of the constructor). This one is not derived from PersistentEObject.

However, the DirectStoreList implicitly expects a PersistentEObject via its delegation to an eStore(). In my test case this is a TransientStoreAdapter, which tries to call 
ReferenceConverter.convert(PersistentEObject.from( notPersistentEObject)).

This causes a 
"java.lang.NoSuchMethodError: org.eclipse.emf.ecore.impl.EStringToStringMapEntryImpl.id()Lfr/inria/atlanmod/neoemf/core/Id;"

I didn't encounter this one directly as it gets caught. The exception handling then throws the UnsupportedOperationException in PersistentEObjectInterceptor.resolve.

There are a couple of "// FIXME Does not resolve" comments in DirectStoreList, which I suspect point to this issue.

I don't know whether DirectStoreList should cope with non-PersistentEObject on its own, whether a different store type should back the list, or whether the Entry class should implement PersistentEObject, but I hope this blurb was helpful in finding the best resolution for this issue.

**Comment by sunye** [comment]
Dear Paul,

    I checked you code and it seems to me that there are several misunderstandings about NeoEMF, its purpose and its usage.

To begin with, you didn't specify any database backend for your EMF Resource. I suggest that you first read the [Get Start wiki page]:(https://github.com/atlanmod/NeoEMF/wiki/Get-Started).

The exception  `NoSuchMethodError` was correctly thrown, because the property you are trying to access, `sCL`, is specified as "derived, transient, and volatile". In other words, this mean that you must implement the methods that access and modify this property.  And that it will not be persisted.

I changed this property, regenerated the code and updated your code to make it compatible with the current SNAPSHOT version. The following code works fine for me:

```java
		URI uri = new BlueprintsUriFactory().createLocalUri("models/document.graphdb");
		ResourceSet resourceSet = new ResourceSetImpl();
		Resource resource = resourceSet .createResource(uri);
		ImmutableConfig config = new BlueprintsTinkerConfig();
		SclFactory factory = SclFactory.eINSTANCE;
		DocumentRoot documentRoot = factory.createDocumentRoot();
		SCLType root = factory.createSCLType();
		documentRoot.getSCL().add(root);
		resource.getContents().add(documentRoot);

                // Resource saving
		resource.save(config.toMap());
		resource.unload();

                // Resource loading
		resource.load(config.toMap());
		DocumentRoot readRoot = (DocumentRoot) resource.getContents().get(0);
		SCLType readType = readRoot.getSCL().get(0);
		resource.unload();
```

**Comment by paulreuter** [comment]
Dear Gerson,

thank you for looking into the code. I do believe there are some mutual misunderstandings. I hope that this email can convince you that I am not as inexperienced or clueless as you may think, and that the issues I am reporting are indeed issues that deserve fixing.

A quick summary of why I want to use NeoEMF for context:

Our software is an engineering tool. The model data can grow uncomfortably large for big projects, and is slated to grow much larger. Just to give you an approximation of the data scope, the largest XML exported so far was ~5 million lines. Having the model lazily-loadable in a database will help to alleviate memory problems. If replacing some expensive traversals with database queries nets us runtime improvements, that would be a welcome bonus. 

However, we still need the ability to (partially or fully) serialize to XML, for data exchange with other tools via web services and files. This is not a day-to-day operation, but will occasionally be required.

You may think the examples or situations I used in the Issue reporting were convoluted or artificial and will not reasonably occur during regular use, but I encountered all of the reported issues (and some more that I didn't have time to properly describe yet) during the following workflow:

1.) Load mid-sized project from XML
2.) Migrate to PersistentResource ( mostly MapDB so far )
3.) Do some well defined changes on the data
4.) Export changed data as XML and compare with known good export

In the particular issue that prompted your reply, the problem I was isolating occurs during the export step, independent of whether steps 2 & 3 are included.  Therefore I reduced the test case to the essential elements to reproduce the issue, even if those are outside of expected or typical use cases.


There is also your reply in issue #92 that I would prefer to comment on in private communication:

Why the posted model is the way it is:
The sCL feature is intentionally "derived, transient, and volatile". It was generated this way by the EMF tools when importing ecore from xsd, and is the standard way of EMF specifying "this content is well-defined but stored in a feature map", in contrast to AnyType feature maps that house unknown content. Accessing this feature will at some point result in a call to BasicExtendedMetadata.getAffiliation( eClass, eStructuralFeature ), which will return the "mixed" feature map of the DocumentRoot. Then, the SCL element is correctly stored and persisted via the feature map, no additional implementation required. On inspection of the memory contents using standard EMF, I can verify that the SCL element is indeed contained as a feature map entry in the "mixed" feature. I have also verified that this works in the NeoEMF implementation as well, and it is not the source of the bug.


The current state in NeoEMF integration on my side:
I am using a locally-built version of NeoEMF where I fixed all of the issues that I encountered so far, as well as extending the feature map support (there are some regular use cases for feature maps that are not covered by the current implementation). With this version, I can successfully import, export, persist and manipulate our data model (with some minor issues left). 

Understandably, I would prefer to merge these changes in the main trunk of NeoEMF instead of having to maintain a fork. Some are trivial bugfixes that are straightforward to verify. Some involve design decisions that will need to be double checked. There also may be some ugly hacks that require rewriting (with some assistance from a NeoEMF expert). There are two issues that need some architectural changes or interface extensions in unrelated classes, or possible a different approach to solve.

What are your preferences on how to proceed in this situation? I am open to any suggestions.


Kind regards,
Paul
