### ISSUE TITLE
Can I integrate it with existing emf libs like eclipse uml2 to benefit from it.

### ISSUE THREAD

**Issue by loongbest** [atlanmod/NeoEMF#93]
I'm using eclipse uml2, which is based on emf facilities. I just wonder can I easily integrate it with existing compiled '.jar' libs? Or I need modify the source code and build myself ?
Is there any tutorial that guide me to do so?

**Comment by sunye** [comment]
Hi Loongbest,

NeoEMF, as well as other persistence layers,  modifies the EMF generated code. So, no, you can't integrate it to existing generated code, you must regenerate the code. 

Take a look at: https://github.com/atlanmod/NeoEMF/wiki/Get-Started
