### ISSUE TITLE
Feature maps, XMLResource and EcoreUtil.copy don't work together

### ISSUE THREAD

**Issue by paulreuter** [atlanmod/NeoEMF#95]
After the copy of a model object with a feature map is added to an XMLResource, the first access to a grandchild (whose parent is stored in the feature map) causes a NoSuchElementException.
The very same grandchild resolves fine before adding to the resource.

A workaround is to add the copy to a different kind of PersistentResource. Afterwards it can be moved to the XMLResource without problem.

Is there a different, recommended way to get an XML serialization?

**Comment by paulreuter** [comment]
Ok, I have had some time for additional research.

The issue is much more general than the conditions mentioned above, and is not even related to FeatureMaps. The underlying cause are missing ClassBeans.

Generally, they should get added in AbstractStoreAdapter.updateInstanceOf. However, there is an optimization that assumes that objects in the cache already have their metaclass stored as a ClassBean. 

This assumption is not generally true as I found through debugging. Some operations add the object to the cache without first adding the metaclass. Most notably DirectStoreList.add . If one of those gets called first, the ClassBean won't ever be created.

**Comment by paulreuter** [comment]
This is fairly easy to produce:

Create parent
Create child
Create grandchild

Add grandchild to child before adding child to parent or setting an attribute on child -> bug

Any news on this?

**Comment by sunye** [comment]
Dear Paul,

The recommended way to get a correct XML serialization is not to use NeoEMF.  The goal of NeoEMF is to store EMF resources in NoSQL databases, such as Neo4j or BerkeleyDB.

If you want to use XML serialization, you may just use EMF.

Best regards,

Gerson
