### ISSUE TITLE
How is proxy references are handled in NeoEMF

### ISSUE THREAD

**Issue by KarthikKenny** [atlanmod/NeoEMF#97]
I have a instance of the model which contains lot of proxy references.

1. I load a file _myfile.myext_ into DB
2. Perform some modification. Save it
3. Again load the DB file back into the Model
4. Save it into _mysecondfile.myext_

Now the problem is that in the step 4 above, proxy URIs are not properly propagated into the Objects created in the Persistence Resource. Due to which I'm not able to serialize the XML tags in a way it was there in the original file. 

Am I missing something? Is there any way where I can persist the Proxy URI?

**Comment by KarthikKenny** [comment]
Do we have any solution here? I'm stuck with this issue for past two days. Any hint / solution would be helpful. Thanks in advance.

**Comment by gdaniel** [comment]
Indeed, proxy references are not well supported in NeoEMF for now. You can basically reference PersistentObjects as proxies, but you can't store proxy references in NeoEMF.

So I am afraid that there is no good solution right now, excepted if the latest release includes something specific about proxy management I didn't see. In that case @sunye and/or @yvernageau may help you.
