### ISSUE TITLE
Deleting elements does not work

### ISSUE THREAD

**Issue by philip-iii** [atlanmod/NeoEMF#98]
It seems like neither `EcoreUtil.deleteAll(resource.getContents(), true)` nor `resource.delete(Collections.emptyMap())` have an effect.

They seem to work for deleting objects added since the resource was loaded. Also `resource.isModified()` returns `false`. Is deleting elements / contents in a resource supported or am I doing something wrong?

**Comment by philip-iii** [comment]
If anyone else is struggling with that, I discovered that `resource.getContents().retainAll(Collections.emptyList())` or `resource.getContents().remove(0)` (for individual objects) seem to do the trick, although it will be more straightforward to be able to also use the `delete` methods as well. Also, `resource.getContents().removeAll(resource.getContents())`doesn't work either. Both `retainAll` and `removeAll` are optional according to the documentation so it would be helpful to know what is implemented and works and what doesn't.

**Comment by sunye** [comment]
Dear Philip,

For some unknown reason, `EcoreUtil.deleteAll()` does not delete any content. However, `resource.getContents().clear()` works fine. 

`EcoreUtil` seems to call some specific method that does not behave as expected in a persistent resource. I will dig deeper when I have some free time.

Regards,

Gerson
