### ISSUE TITLE
Support for Elasticsearch?

### ISSUE THREAD

**Issue by Sandared** [atlanmod/NeoEMF#99]
Hi,

I just wanted to ask if you plan to support Elasticsearch as a possible backend or if such support is not on your roadmap.

Kind regards,
Thomas

**Comment by sunye** [comment]
Dear Sandared,

Unfortunately, we have no plans to support Elasticsearch in a near future.  However, if you want to develop a new backend for NeoEMF, we would be happy to help you understand NeoEMF's architecture.

Best regards,

Gerson Sunyé
